update python/django support: add django 2.2
django-compressor/django-appconf pull request #47
Opened 2019-04-16 14:56 UTC by Niouby

2019-04-29 08:51 UTC, hsmett approved these changes
lgtm

2019-07-11 08:19 UTC, mrunge commented
This fails in tox:
```
&cache=shared')...
SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E410) 'django.contrib.sessions.middleware.SessionMiddleware' must be in MIDDLEWARE in order to use the admin application.

System check identified 1 issue (0 silenced).
ERROR: InvocationError for command '/home/mrunge/tmp/django-appconf/.tox/py35-dj22/bin/coverage run /home/mrunge/tmp/django-appconf/.tox/py35-dj22/bin/django-admin.py test -v2 tests' (exited with code 1)
```

2019-07-11 08:25 UTC, mrunge requested changes
Could you please add this as well? This makes tox pass for me.

2019-07-11 08:25 UTC, mrunge commented on tests/test_settings.py
> +    "django.contrib.messages.middleware.MessageMiddleware",
also add "django.contrib.sessions.middleware.SessionMiddleware",

2019-07-11 08:50 UTC, hsmett commented
E410 was added in django 2.2.1, which is the reason why travis didn't complain at the time.

[](https://docs.djangoproject.com/en/2.2/releases/2.2.1/)

2019-07-11 08:58 UTC, mrunge commented
Right. Thank you for the context. 

This patch (plus the additional line) made django-appconf build and pass tests during build on Fedora infrastructure.

2019-07-11 09:18 UTC, mrunge approved these changes
Thank you, this looks good to me!

2019-07-11 09:23 UTC, carltongibson approved these changes
OK, super, looks good. Thank you.

2019-07-11 09:23 UTC, merged

2019-07-11 09:31 UTC, Niouby commented
thanks ^^